[package]
name = "kape-example-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
dotenv.workspace = true
kape.workspace = true
kape-postgres.workspace = true
kape-testkit.workspace = true
sqlx.workspace = true
tokio.workspace = true

[lints]
workspace = true
