[package]
name = "kape-example-custom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
kape.workspace = true
kape-testkit.workspace = true
tokio.workspace = true

[lints]
workspace = true
